### ISSUE TITLE
Examples of stream please?

### ISSUE THREAD

**Issue by ttodua** [LCuretti/Ameritrade-Interface#2]
hi.
I've checked the stream examples, but when i run:

TDS.data_request_timesale_equity(command = "SUBS", keys = 'AAPL', fields = '0,1,2,3,4')  

Heartbeat at: 2020-02-07 23:33:11.246
TIMESALE_EQUITY SUBS command succeeded at: 2020-02-07 23:33:11.246
Press any key to continue . . .

so, it doesnt run (forever) to stream the websocket updates and print it.
how to achieve that, can you give some example code line ?

(i mean, i want it the websocket connection to keep open and print the incoming data from websocket)

**Comment by LCuretti** [comment]
[Timesales_Equity_2019-12-09_.xlsx](https://github.com/LCuretti/Ameritrade-Interface/files/4174169/Timesales_Equity_2019-12-09_.xlsx)

hi,
Just in case there is an environment issue I am using Spyder/Anaconda on Windows system.
I will check if the behavior is the same on VS/Anaconda.

I assume you have TD account and TD developer account, plus 
TDAuthentication, TDAPI, worked fine since you get the success subscription.

When I run the first part of  TDStrem-Test.py
I haven't ever get the "Press any key to continue . . ." message.
After I get the "TIMESALE_EQUITY SUBS command succeeded at: ..." message the system keeps streaming and storing on csv file with a Heartbeat every 10 min if data is streaming or every 10 sec if no data to stream. Till I stop it. 

Example:
from TDStream import TDStreamerClient
from Ameritrade_cfg import client_id, redirect_uri, account_id
TDS = TDStreamerClient(client_id, redirect_uri, account_id)
TDS.connect()
TDS.data_request_timesale_equity(command = "SUBS", keys = '/AAPL, MELI, GOOG, AMZN', fields = '0,1,2,3,4')


TDAuthentication Initialized at: 2020-02-08 08:51:09.381238
TDAPI Initialized at: 2020-02-08 08:51:10.293290
TDStream Initialized at: 2020-02-08 08:51:10.293290
Logged in at: 2020-02-08 08:51:37.286
Heartbeat at: 2020-02-08 08:51:38.446
TIMESALE_EQUITY SUBS command succeeded at: 2020-02-08 08:51:38.446
Heartbeat at: 2020-02-08 08:51:48.579
Heartbeat at: 2020-02-08 08:51:58.582
Heartbeat at: 2020-02-08 08:52:08.584
Heartbeat at: 2020-02-08 08:52:18.586


Regarding on printing instead of storing,
you can change line 271 on TDStream.py

from: 
        self.response_types['data'].append(content)

to:
        print(content)

Please let me know your environment. I know spyder is built in asyncio so if you use another you may need to import asyncio library.

regards

**Comment by ttodua** [comment]
thank you. you were right, i've traced down and found that 271 line to execute the function on each response. thanks!
